### ISSUE TITLE
uncertainty 的公式怎么理解

### ISSUE THREAD

**Issue by LLLLLLoki** [autoliuweijie/FastBERT#5]
感谢您分享出论文的代码与做出的贡献，我在阅读代码与论文的时候有一个问题，在Adaptive inference中的uncertainty公式怎么理解呢，为什么可以这样确定结果的不确定性

**Comment by autoliuweijie** [comment]
本文中的uncertainty定义为标准化后的熵。

在信息论中，熵用于描述一个随机变量的不确定度。

**Comment by LLLLLLoki** [comment]
谢谢哈

**Comment by hurricanedjp** [comment]
distillation是使用了各层与最后一层之间的相对熵的和作为loss，inference时各层的uncertainty定义为标椎化后的熵，请问下这之间有什么公式推导关系么？总感觉有些联系。
并且如果使用熵做不确定度的话，为何要标准化除以log(1/N)，这是基于怎样的考虑呢？
