### ISSUE TITLE
关于文章中的FLOPs计算

### ISSUE THREAD

**Issue by NeoZzh** [autoliuweijie/FastBERT#6]
你好，

请问文章里表2中所列BERT/DistilBERT的FLOPs是否包括最后的classifier，即在CLS后面接的那个MLP？这部分的FLOPs应该和最后的label个数N有关吧？另外，文章中的FLOPs是用什么工具计算的？

谢谢

**Comment by autoliuweijie** [comment]
列表2中FLOPs包括最后的classifier，这部分的FLOPs与label个数N有关，但是这部分的FLOPs特别小，几乎不影响整个模型的FLOPs。

FLOPs可以使用python的htop工具计算

```python
from thop import profile

flops, params = profile(model, inputs, verbose=False)
```
